// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rpbnb_build_flags_cpp
Rcpp::List rpbnb_build_flags_cpp();
RcppExport SEXP _rpbnb_rpbnb_build_flags_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rpbnb_build_flags_cpp());
    return rcpp_result_gen;
END_RCPP
}
// pbivnorm_cpp
NumericVector pbivnorm_cpp(NumericVector h, NumericVector k, double rho);
RcppExport SEXP _rpbnb_pbivnorm_cpp(SEXP hSEXP, SEXP kSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type h(hSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(pbivnorm_cpp(h, k, rho));
    return rcpp_result_gen;
END_RCPP
}
// rpbnb_copula_ll_grad_cpp
List rpbnb_copula_ll_grad_cpp(NumericVector y1, NumericVector y2, NumericMatrix X1, NumericMatrix X2, NumericMatrix XR1, NumericMatrix XR2, IntegerVector rand_idx1, IntegerVector rand_idx2, NumericMatrix dev1, NumericMatrix dev2, NumericMatrix dloc1, NumericMatrix dloc2, NumericMatrix dscale1, NumericMatrix dscale2, NumericVector xb1, NumericVector xb2, double r1, double r2, double theta, double dth_dz, int family_code, int want_scores, int num_threads);
RcppExport SEXP _rpbnb_rpbnb_copula_ll_grad_cpp(SEXP y1SEXP, SEXP y2SEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP XR1SEXP, SEXP XR2SEXP, SEXP rand_idx1SEXP, SEXP rand_idx2SEXP, SEXP dev1SEXP, SEXP dev2SEXP, SEXP dloc1SEXP, SEXP dloc2SEXP, SEXP dscale1SEXP, SEXP dscale2SEXP, SEXP xb1SEXP, SEXP xb2SEXP, SEXP r1SEXP, SEXP r2SEXP, SEXP thetaSEXP, SEXP dth_dzSEXP, SEXP family_codeSEXP, SEXP want_scoresSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y2(y2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type XR1(XR1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type XR2(XR2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type rand_idx1(rand_idx1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type rand_idx2(rand_idx2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dev1(dev1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dev2(dev2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dloc1(dloc1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dloc2(dloc2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dscale1(dscale1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dscale2(dscale2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xb1(xb1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xb2(xb2SEXP);
    Rcpp::traits::input_parameter< double >::type r1(r1SEXP);
    Rcpp::traits::input_parameter< double >::type r2(r2SEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type dth_dz(dth_dzSEXP);
    Rcpp::traits::input_parameter< int >::type family_code(family_codeSEXP);
    Rcpp::traits::input_parameter< int >::type want_scores(want_scoresSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(rpbnb_copula_ll_grad_cpp(y1, y2, X1, X2, XR1, XR2, rand_idx1, rand_idx2, dev1, dev2, dloc1, dloc2, dscale1, dscale2, xb1, xb2, r1, r2, theta, dth_dz, family_code, want_scores, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// get_num_threads
int get_num_threads();
RcppExport SEXP _rpbnb_get_num_threads() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_num_threads());
    return rcpp_result_gen;
END_RCPP
}
// set_rcpp_parallel_threads
void set_rcpp_parallel_threads(int n_threads);
RcppExport SEXP _rpbnb_set_rcpp_parallel_threads(SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    set_rcpp_parallel_threads(n_threads);
    return R_NilValue;
END_RCPP
}
// rpbnb_openmp_enabled
bool rpbnb_openmp_enabled();
RcppExport SEXP _rpbnb_rpbnb_openmp_enabled() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rpbnb_openmp_enabled());
    return rcpp_result_gen;
END_RCPP
}
// rpbnb_ll_grad_cpp
List rpbnb_ll_grad_cpp(NumericVector y1, NumericVector y2, NumericMatrix X1, NumericMatrix X2, NumericMatrix XR1, NumericMatrix XR2, IntegerVector rand_idx1, IntegerVector rand_idx2, NumericMatrix dev1, NumericMatrix dev2, NumericMatrix dloc1, NumericMatrix dloc2, NumericMatrix dscale1, NumericMatrix dscale2, NumericVector xb1, NumericVector xb2, NumericVector S1, NumericVector S2, double m1, double m2, double zlam, int want_grad, int use_fixed, double lamLo_in, double lamHi_in, int want_scores, int num_threads);
RcppExport SEXP _rpbnb_rpbnb_ll_grad_cpp(SEXP y1SEXP, SEXP y2SEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP XR1SEXP, SEXP XR2SEXP, SEXP rand_idx1SEXP, SEXP rand_idx2SEXP, SEXP dev1SEXP, SEXP dev2SEXP, SEXP dloc1SEXP, SEXP dloc2SEXP, SEXP dscale1SEXP, SEXP dscale2SEXP, SEXP xb1SEXP, SEXP xb2SEXP, SEXP S1SEXP, SEXP S2SEXP, SEXP m1SEXP, SEXP m2SEXP, SEXP zlamSEXP, SEXP want_gradSEXP, SEXP use_fixedSEXP, SEXP lamLo_inSEXP, SEXP lamHi_inSEXP, SEXP want_scoresSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y2(y2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type XR1(XR1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type XR2(XR2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type rand_idx1(rand_idx1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type rand_idx2(rand_idx2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dev1(dev1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dev2(dev2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dloc1(dloc1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dloc2(dloc2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dscale1(dscale1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dscale2(dscale2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xb1(xb1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xb2(xb2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type S1(S1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type S2(S2SEXP);
    Rcpp::traits::input_parameter< double >::type m1(m1SEXP);
    Rcpp::traits::input_parameter< double >::type m2(m2SEXP);
    Rcpp::traits::input_parameter< double >::type zlam(zlamSEXP);
    Rcpp::traits::input_parameter< int >::type want_grad(want_gradSEXP);
    Rcpp::traits::input_parameter< int >::type use_fixed(use_fixedSEXP);
    Rcpp::traits::input_parameter< double >::type lamLo_in(lamLo_inSEXP);
    Rcpp::traits::input_parameter< double >::type lamHi_in(lamHi_inSEXP);
    Rcpp::traits::input_parameter< int >::type want_scores(want_scoresSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(rpbnb_ll_grad_cpp(y1, y2, X1, X2, XR1, XR2, rand_idx1, rand_idx2, dev1, dev2, dloc1, dloc2, dscale1, dscale2, xb1, xb2, S1, S2, m1, m2, zlam, want_grad, use_fixed, lamLo_in, lamHi_in, want_scores, num_threads));
    return rcpp_result_gen;
END_RCPP
}
