# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rpbnb_build_flags_cpp <- function() {
    .Call(`_rpbnb_rpbnb_build_flags_cpp`)
}

pbivnorm_cpp <- function(h, k, rho) {
    .Call(`_rpbnb_pbivnorm_cpp`, h, k, rho)
}

rpbnb_copula_ll_grad_cpp <- function(y1, y2, X1, X2, XR1, XR2, rand_idx1, rand_idx2, dev1, dev2, dloc1, dloc2, dscale1, dscale2, xb1, xb2, r1, r2, theta, dth_dz, family_code, want_scores, num_threads) {
    .Call(`_rpbnb_rpbnb_copula_ll_grad_cpp`, y1, y2, X1, X2, XR1, XR2, rand_idx1, rand_idx2, dev1, dev2, dloc1, dloc2, dscale1, dscale2, xb1, xb2, r1, r2, theta, dth_dz, family_code, want_scores, num_threads)
}

get_num_threads <- function() {
    .Call(`_rpbnb_get_num_threads`)
}

set_rcpp_parallel_threads <- function(n_threads) {
    invisible(.Call(`_rpbnb_set_rcpp_parallel_threads`, n_threads))
}

rpbnb_openmp_enabled <- function() {
    .Call(`_rpbnb_rpbnb_openmp_enabled`)
}

rpbnb_ll_grad_cpp <- function(y1, y2, X1, X2, XR1, XR2, rand_idx1, rand_idx2, dev1, dev2, dloc1, dloc2, dscale1, dscale2, xb1, xb2, S1, S2, m1, m2, zlam, want_grad, use_fixed, lamLo_in, lamHi_in, want_scores, num_threads) {
    .Call(`_rpbnb_rpbnb_ll_grad_cpp`, y1, y2, X1, X2, XR1, XR2, rand_idx1, rand_idx2, dev1, dev2, dloc1, dloc2, dscale1, dscale2, xb1, xb2, S1, S2, m1, m2, zlam, want_grad, use_fixed, lamLo_in, lamHi_in, want_scores, num_threads)
}

